### PR TITLE
🧑‍💻: Added Prettier tailwind, updated Huksy Pre-Commit & changed files accordlingly

### PR DESCRIPTION
**Pull request by xannyxs**
All developers should install prettier-tailwind on their machine. Husky is now updated, and should work again.

### CODE REVIEW

**Comment by Mario-SO** [comment]
Provide a link to the extension so we all make sure to have the exact same one

**Comment by xannyxs** [comment]
@Mario-SO 

27:13  Error: `'` can be escaped with `&apos;`, `&lsquo;`, `&#39;`, `&rsquo;`.  react/no-unescaped-entities

**Comment by xannyxs** [comment]
I followed this guide from the official page:

https://tailwindcss.com/blog/automatic-class-sorting-with-prettier

**Comment by Mario-SO** [comment]
Oh I thought it was an extension, not an actual npm library.

**Comment by xannyxs** [comment]
This package serves dual purposes:

1. It functions as an extension for development environments.
2. It ensures consistent installation across all development setups.

- Enables `.husky` to perform pre-push checks for:
  - Prettier formatting
  - Linting
- Includes the Tailwind package, which is necessary for these checks

**Review by Mario-SO — APPROVED** [review]

**Comment by Mario-SO** [comment]
We really need to find a way around the `yarn.lock` file...

**Pull request merged**
