### PR TITLE
cypress test update

### PR DESCRIPTION
**Pull request by greatsamist**

### CODE REVIEW

**Comment by xannyxs** [comment]
@greatsamist Can I take this over?

**Comment by greatsamist** [comment]
> @greatsamist Can I take this over?

sure

**Comment by xannyxs** [comment]
@greatsamist can you review this please?

**Review by greatsamist — COMMENTED** [review]
had some hard times getting the watch test to pass which works locally, we can revisit it later. 
In general, great work on the new added tests

**Comment by xannyxs** [comment]
Cypress Servers do run the `watch` test without any issues.

**Pull request merged**
