### PR TITLE
MetaData for homepage

### PR DESCRIPTION
**Pull request by xvoorvaa**

### CODE REVIEW

**Comment by pabloVoorvaart** [comment]
this pr should be addressing is addressing ticket #148 

This ticket specifies that we should generate metadata for all pages, including custom metadata for event pages. For instance if im sharing the solidity summit event page, we should get metadata specific for the solidtity summit event. 


Home page behaviour is good, but I would change a few things: 

share image should be the full 16:9 streameth cover that Filippo made. 
tag line should be: streameth, the complete solution to host your hybrid or virtual event.

currently its like this: 

Screenshot 2023-11-07 at 12 25 04

**Comment by wslyvh** [comment]
FYI - share images on Twitter should actually be 2:1 for type summary_card (or summary_card_large)
https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/summary-card-with-large-image

**Comment by pabloVoorvaart** [comment]
I think the stage page is missing @xvoorvaa

**Comment by xvoorvaa** [comment]
Mine is working:
https://streameth-platform-96wwswyu4-streameth.vercel.app/zuzalu/zuconnect__decentralized_social_track/stage/theater

**Comment by pabloVoorvaart** [comment]
can we add the event cover image there?

**Review by pabloVoorvaart — APPROVED** [review]

**Comment by pabloVoorvaart** [comment]
@xvoorvaa this should be merged into dev

**Pull request closed without merging**
