### PR TITLE
✨ Fix #807 - Improve the user onboarding experience

### LINKED ISSUE #807: [TASK] Improve the user onboarding experience
## Description

First disable the create account

Change the user onboarding as follows:
- Event onboarding starts on the website, where users can either click the "create event" button or the "explore" button.
- If users click the "create event" button, they go to our current login screen.
- In our current login screen, modify it as follows:
  - Existing users can log in as normal.
  - New users cannot log in or create an account, but they can leave their email if they want to create an account.
  - Show an "explore" button that takes users to the explore page.

## Related User Story
None

## Objectives
- [ ] Update the website to include the "create event" and "explore" buttons on the onboarding page.
- [ ] Modify the current login screen to differentiate between existing and new users.
- [ ] Add functionality for new users to leave their email for account creation.
- [ ] Add an "explore" button on the login screen to redirect users to the explore page.

## Acceptance Criteria
- [ ] Website onboarding page has "create event" and "explore" buttons.
- [ ] Existing users can log in as normal on the login screen.
- [ ] New users cannot log in or create an account but can leave their email.
- [ ] Login screen includes an "explore" button that redirects to the explore page.

## Additional Information
Ensure the user experience is smooth and intuitive, with clear instructions for both existing and new users. Any design changes should be consistent with the current website's style and branding.

### PR DESCRIPTION
**Pull request by greatsamist**
# Pull Request Info

## Description
This PR enhances user onboarding by disabling account creation for new users on the login screen, updating the event onboarding page to offer options to either create an event or explore, and modifying the login screen to allow existing users to log in normally while presenting new users with a modal with a create event button that initiates the account creation flow.

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published

## Screenshots 
image
image

### CODE REVIEW

**Comment by pblvrt** [comment]
LGTM, but when I try to login with a non existing account I get this: 
Screenshot 2024-07-30 at 17 58 06



tried both email and metamask

**Comment by Mario-SO** [comment]
> LGTM, but when I try to login with a non existing account I get this: 
> 
> Screenshot 2024-07-30 at 17 58 06
> 
> 
> 
> 
> 
> 
> 
> tried both email and metamask

I was going to improve a bit the modal that appears when a user is not found. Today around 7-8 pm i will arrive home and will work on this a bit.

**Comment by pblvrt** [comment]
ok but really need this in prod today @Mario-SO

**Comment by Mario-SO** [comment]
> ok but really need this in prod today @Mario-SO 

🥲

**Comment by Mario-SO** [comment]
New No user found dialog

CleanShot 2024-07-30 at 17 01 04@2x

**Comment by greatsamist** [comment]
New modal LGTM

**Review by Mario-SO — APPROVED** [review]

**Pull request merged**
