### PR TITLE
🥅 Better error pages

### LINKED ISSUE #723: Better generic error page
**Is your feature request related to a problem? Please describe.**
Right now our default error page is pretty bad and has 0 styling.

CleanShot 2024-07-04 at 10 38 44

**Describe the solution you'd like**
I would like a more professional looking error page so at least the user perceives that we are somehow aware of the error.

**Additional context**
This is our current Error page code.

CleanShot 2024-07-04 at 10 39 06

**Screenshots**
Provided above 👆

### PR DESCRIPTION
**Pull request by Mario-SO**
# Pull Request Info

## Description

New error page

Fixes (#723)

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published

## Screenshots:
Before

CleanShot 2024-07-04 at 10 38 44

After
CleanShot 2024-07-04 at 10 50 40

## Additional context:

closes #723

### CODE REVIEW

**Comment by Mario-SO** [comment]
No idea why this is not building...

**Comment by xannyxs** [comment]
@Mario-SO

27:13 Error: ' can be escaped with &apos;, &lsquo;, &#39;, &rsquo;. react/no-unescaped-entities

**Comment by Mario-SO** [comment]
Oh I now remember this error, it is the `'` apostrophe, React doesn't like it.

**Review by greatsamist — APPROVED** [review]

**Comment by pblvrt** [comment]
LGTM but I think that maybe we should add the contact support button here @Mario-SO

**Comment by Mario-SO** [comment]
Ok will do

**Comment by Mario-SO** [comment]
Before


CleanShot 2024-07-05 at 13 06 21@2x


After

Can be heavily improved by incorporating more of our branding, but it is an improvement for now.

CleanShot 2024-07-05 at 13 05 27@2x

**Review by pblvrt — APPROVED** [review]
LGTM

**Pull request merged**
