### PR TITLE
🔧 Updated `prettierrc.json` file

### PR DESCRIPTION
**Pull request by Mario-SO**
Before

```json
{
  "trailingComma": "es5",
  "semi": false,
  "singleQuote": true,
  "printWidth": 70, 
  "bracketSameLine": true
}
```

After

```json
{
  "trailingComma": "es5",
  "semi": true,
  "singleQuote": true,
  "printWidth": 80,
  "tabWidth": 2,
  "useTabs": false,
  "bracketSpacing": true,
  "bracketSameLine": false,
  "arrowParens": "always",
  "endOfLine": "lf",
  "quoteProps": "as-needed",
  "jsxSingleQuote": false,
  "proseWrap": "preserve",
  "htmlWhitespaceSensitivity": "css"
}
```
1. Common settings:
   Both configurations share these settings:
   - `"trailingComma": "es5"`: Adds trailing commas where valid in ES5 (objects, arrays, etc.).
   - `"singleQuote": true`: Uses single quotes instead of double quotes.

2. Differences and improvements in the new configuration:

   a. `"semi": true` vs `"semi": false`:
   - The new config uses `true`, which adds semicolons at the end of statements.
   - Justification: Adding semicolons is generally considered safer, as it prevents potential issues with Automatic Semicolon Insertion (ASI) and makes the code more explicit.

   b. `"printWidth": 80` vs `"printWidth": 70`:
   - The new config uses 80 characters, which is a widely accepted standard.
   - Justification: 80 characters is a good balance between readability and screen space utilization. 70 might be too narrow for modern screens and could lead to unnecessary line breaks.

   c. `"bracketSameLine": false` vs `"bracketSameLine": true`:
   - The new config puts the `>` of a multi-line JSX element on a new line.
   - Justification: This improves readability by clearly separating the opening and closing tags of JSX elements.

   d. Additional beneficial settings in the first config:
   - `"tabWidth": 2` and `"useTabs": false`: Ensures consistent indentation using 2 spaces.
   - `"bracketSpacing": true`: Adds spaces between brackets in object literals, improving readability.
   - `"arrowParens": "always"`: Always includes parentheses around a sole arrow function parameter.
   - `"endOfLine": "lf"`: Uses LF (Line Feed) for consistent line endings across different operating systems.
   - `"quoteProps": "as-needed"`: Only adds quotes around object properties when necessary.
   - `"jsxSingleQuote": false`: Uses double quotes in JSX, which is more common in React communities.
   - `"proseWrap": "preserve"`: Respects the original line breaks in markdown or prose.
   - `"htmlWhitespaceSensitivity": "css"`: Respects CSS display property in HTML formatting.

### CODE REVIEW

**Comment by xannyxs** [comment]
@Mario-SO Should we also change the files accordingly?

**Comment by Mario-SO** [comment]
@xannyxs I don't get what you mean exactly... The `.prettierrc.json` file is not in the `.gitignore` so when this gets merged, we all should have the same config.

**Comment by xannyxs** [comment]
> @xannyxs I don't get what you mean exactly... The `.prettierrc.json` file is not in the `.gitignore` so when this gets merged, we all should have the same config.

Sorry, I meant if we should also change the files to the new prettier format

**Comment by Mario-SO** [comment]
Closing this due to constant merge conflicts. Please @xannyxs @Eric-Vondee @greatsamist @pblvrt copy the `.prettierrc.json` file in the PR description and check once done, will close when everyone has done it.

- [ ] @Mario-SO 
- [ ] @xannyxs 
- [ ] @pblvrt 
- [ ] @Eric-Vondee 
- [ ] @greatsamist

**Comment by xannyxs** [comment]
@Mario-SO I think you should just merge and tell everyone that they need to merge `ours` and then use `yarn:pretter:fix`

**Comment by xannyxs** [comment]
Also something I just realise, but maybe we should just have one `prettierrc.json` in the root, don't you think?

**Comment by Mario-SO** [comment]
> @Mario-SO I think you should just merge and tell everyone that they need to merge `ours` and then use `yarn:pretter:fix`

The thing is the merge conflicts, I prefer to close this one and tomorrow in the daily, tell everyone to get this prettierrc

**Pull request closed without merging**
